CREATE DATABASE QUANLISACH
GO
USE QUANLISACH
GO


CREATE TABLE SACH
(
	id nvarchar(100) PRIMARY KEY,
	TEN NVARCHAR(100) ,
	THELOAI NVARCHAR(100),
	NOIDUNGSOBO NVARCHAR(1000),
)
GO


CREATE TABLE THELOAISACH
(
	ID NVARCHAR(100) PRIMARY KEY,
	TENTHELOAI NVARCHAR(100)

)
GO



CREATE TABLE TAIKHOAN
(
	taikhoan NVARCHAR(100) PRIMARY KEY,	
	matkhau NVARCHAR(100),
	
)
GO

--- KHÓA NGOẠI---
ALTER TABLE dbo.SACH
ADD CONSTRAINT FK_SACH_THELOAISACH
		FOREIGN KEY (THELOAI)
		REFERENCES dbo.THELOAISACH(id)
GO

-------NHAP THONG TIN-----
INSERT INTO dbo.TAIKHOAN

VALUES  (  N'ADMIN', -- TEN NGƯƠI DÙNG---
		   N'123'--MẬT KHẨU--
		   )
GO

INSERT INTO dbo.THELOAISACH

VALUES  ( '001' , -- MA - 
        
           N'SGK' -- THELOLAI---
		   )
GO


INSERT INTO dbo.SACH

VALUES  ( '012345' , -- MA - 
          N'LE CHU BAU' , -- TENSACH - 
           N'001', -- THELOLAI---
		   N'asjlkdnflkjalkjasdnflk;á;ldf'--NOI DUNG SỢ BỘ---
         
        )
GO